Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using onni.Models;

namespace onni.Controllers
{
	[Authorize(Roles = "Admin")]
	public class CategoriesController : Controller
    {
        private readonly ChangeMakingContext _context;

        public CategoriesController(ChangeMakingContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categories = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoriesId == id);
            if (categories == null)
            {
                return NotFound();
            }

            return View(categories);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoriesId,CategoriesName")] Categories categories)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categories);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categories);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categories = await _context.Categories.FindAsync(id);
            if (categories == null)
            {
                return NotFound();
            }
            return View(categories);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoriesId,CategoriesName")] Categories categories)
        {
            if (id != categories.CategoriesId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categories);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriesExists(categories.CategoriesId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categories);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categories = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoriesId == id);
            if (categories == null)
            {
                return NotFound();
            }

            return View(categories);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categories = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(categories);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriesExists(int id)
        {
            return _context.Categories.Any(e => e.CategoriesId == id);
        }
    }
}

Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using onni.Models;

namespace onni.Controllers
{
	//[Authorize(Roles = "Admin,Collaborator,Creator")]

	public class CommentsController : Controller
    {
        private readonly ChangeMakingContext _context;

        public CommentsController(ChangeMakingContext context)
        {
            _context = context;
        }

        // GET: Comments
        public async Task<IActionResult> Index()
        {
            var changeMakingContext = _context.Comments.Include(c => c.Project);
            return View(await changeMakingContext.OrderByDescending(p => p.CommentDate).ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comments = await _context.Comments
                .Include(c => c.Project)
                .FirstOrDefaultAsync(m => m.CommentId == id);
            if (comments == null)
            {
                return NotFound();
            }

            return View(comments);
        }

        // GET: Comments/Create
        public IActionResult Create()
        {
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectName");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CommentId,UserName,ProjectId,CommentDate,BodyContent")] Comments comments)
        {
            if (ModelState.IsValid)
            {
                _context.Add(comments);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Projects", new { id = comments.ProjectId });
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectName", comments.ProjectId);
            return RedirectToAction("Details", "Projects", new { id = comments.ProjectId });
        }


        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comments = await _context.Comments.FindAsync(id);
            if (comments == null)
            {
                return NotFound();
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectName", comments.ProjectId);
            return View(comments);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CommentId,UserName,ProjectId,CommentDate,BodyContent")] Comments comments)
        {
            if (id != comments.CommentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comments);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentsExists(comments.CommentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectName", comments.ProjectId);
            return View(comments);
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comments = await _context.Comments
                .Include(c => c.Project)
                .FirstOrDefaultAsync(m => m.CommentId == id);
            if (comments == null)
            {
                return NotFound();
            }

            return View(comments);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comments = await _context.Comments.FindAsync(id);
            _context.Comments.Remove(comments);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Projects", new { id = comments.ProjectId });
        }

        private bool CommentsExists(int id)
        {
            return _context.Comments.Any(e => e.CommentId == id);
        }
    }
}

Views/Admin/Index.cshtml
@model IEnumerable<onni.Models.Projects>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Manage Projects</h2>
<td><a asp-controller="Admin" asp-action="Report">Back to Report</a></td>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProjectName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
            <th></th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Projects" asp-action="Details" asp-route-id="@item.ProjectId"> @Html.DisplayFor(modelItem => item.ProjectName)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status.StatusName)
                </td>
                <td>
                    <form asp-area="Admin" asp-action="Public" asp-route-id="@item.ProjectId" method="post">

                        @if (item.StatusId == 1)
                        {
                            <button type="submit" class="btn btn-primary">Publish</button>
                        }
                    </form>
                </td>
                <td>
                    <a class="btn btn-link text-danger" asp-controller="Projects" asp-action="Delete" asp-route-id="@item.ProjectId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Admin/Report.cshtml
@{
    ViewData["Title"] = "Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Administration</h2>



@if (ViewData["PendingProjects"] != null)
{
    <div class="alert alert-secondary">There are @ViewData["PendingProjects"] projects are pending approval <a class=" ml-3 btn btn-primary" asp-action="Index">Approve Now</a></div>
}

    <div class="btn-group mb-3">
        <div class="btn-group">
            <button id="manageGroup" type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Manage
            </button>
            <div class="dropdown-menu" aria-labelledby="manageGroup">
                <a class="dropdown-item" asp-area="" asp-controller="role" asp-action="index">Edit Roles </a>
                <a class="dropdown-item" asp-controller="Categories" asp-action="Index">Edit Categories</a>
                <a class="dropdown-item" asp-controller="Comments" asp-action="Index">Manage Comments</a>
            </div>
        </div>
        <a class="btn btn-outline-primary" asp-action="Index">Approve projects</a>
    </div>


<h3>Activity this month</h3>
<table class="table">
    <tr>
        <th>
            New projects
        </th>
        <th>
            New comments
        </th>
    </tr>
    <tr>
        <td>
            @ViewData["ProjectsCount"]

        </td>
        <td>
            @ViewData["CommentsCount"]

        </td>
    </tr>
</table>

<h3>Activity this year</h3>
<table class="table">
    <tr>
        <th>
            Month
        </th>
        <th>
            New projects
        </th>
        <th>
            New comments
        </th>
    </tr>
    @foreach (var item in (IEnumerable<ActivityInYear>)ViewData["ActivityInYear"])
    {
        var mouthName = new DateTime(2012, item.Month, 1).ToString("MMMM");
        <tr>
            <td>
                @mouthName
            </td>
            <td>
                @item.yearProjects
            </td>
            <td>
                @item.yearComments
            </td>
        </tr>

    }
</table>


@*<h3>New comments this year</h3>
    <table class="table">
        <tr>
            <th>
                Month
            </th>
            <th>
                Count
            </th>
        </tr>
        @foreach (var item in (IEnumerable<CommentsInYear>)ViewData["CommentsInYear"])
        {
            var mouthName = new DateTime(2012, item.Mouth, 1).ToString("MMMM");
            <tr>
                <td>
                    @mouthName
                </td>
                <td>
                    @item.Count
                </td>
            </tr>

        }
    </table>


    <h3>New projects this year</h3>
    <table class="table">
        <tr>
            <th>
                Month
            </th>
            <th>
                Count
            </th>
        </tr>
        @foreach (var item in (IEnumerable<ProjectsInYear>)ViewData["ProjectsInYears"])
        {
            var mouthName = new DateTime(2012, item.Mouth, 1).ToString("MMMM");
            <tr>
                <td>
                    @mouthName
                </td>
                <td>
                    @item.Count
                </td>
            </tr>

        }
    </table>*@

<h3>Top projects this year</h3>
<table class="table">
    <tr>
        <th>
            Most viewed
        </th>
        <th>
            Most liked
        </th>
    </tr>
    @foreach (var record in (IEnumerable<BestOfYear>)ViewData["YearRecords"])
    {
        if (record.views != null)
        {
            <tr>
                <td>
                    <a asp-controller="Projects" asp-action="Details" asp-route-id="@record.views.ProjectId"> @record.views.ProjectName</a>
                    <span>(@record.views.ViewCounts) </span>
                </td>
                <td>
                    <a asp-controller="Projects" asp-action="Details" asp-route-id="@record.likes.ProjectId"> @record.likes.ProjectName</a>
                    <span>(@record.likes.LikeCounts) </span>
                </td>
            </tr>
        }
       
    }
</table>

@*<div>
        <h3>
            Most Liked Projects
        </h3>
        <ol>

            @foreach (var project in (IEnumerable<Projects>)ViewData["MostLiked"])
            {
                <li>
                    <a asp-controller="Projects" asp-action="Details" asp-route-id="@project.ProjectId"> @project.ProjectName</a>
                    <span>(@project.LikeCounts) </span>
                </li>

            }
        </ol>
    </div>


    <div>
        <h3>
            Most viewed Project
        </h3>
        <ol>

            @foreach (var project in (IEnumerable<Projects>)ViewData["MostViewed"])
            {
                <li>
                    <a asp-controller="Projects" asp-action="Details" asp-route-id="@project.ProjectId"> @project.ProjectName</a>
                    <span>(@project.ViewCounts) </span>
                </li>

            }
        </ol>
    </div>*@