Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using onni.Models;

namespace onni.Controllers
{
	[Authorize]
	public class ProjectsController : Controller
	{
		//Used for file upload
		private readonly IHostingEnvironment hostingEnvironment;
		//Add db context
		private readonly ChangeMakingContext _context;

		public ProjectsController(ChangeMakingContext context, IHostingEnvironment environment)
		{
			_context = context;
			hostingEnvironment = environment;
		}

		// GET: Projects
		[AllowAnonymous]
		public async Task<IActionResult> Index(string searchString, string ProjectCategory)
		{
			// https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-2.1
			IQueryable<string> genreQuery = from m in _context.Projects
											orderby m.Category.CategoriesName
											select m.Category.CategoriesName;
			var projects = from p in _context.Projects.Include(p => p.Category).Include(p => p.ParentProject).Include(p => p.Status) select p;
			projects = projects.Where(p => p.StatusId != 1);
			if (!string.IsNullOrEmpty(searchString))
			{
				projects = projects.Where(s => s.ProjectName.Contains(searchString) || s.BodyContent.Contains(searchString) || s.Tags.Contains(searchString));
				ViewBag.searchString =  searchString;
			}
			if (!string.IsNullOrEmpty(ProjectCategory))
			{
				projects = projects.Where(x => x.Category.CategoriesName == ProjectCategory);
				ViewBag.ProjectCategory =  ProjectCategory;
			}

			var ProjectCategorie = new ProjectCategories
			{
				Categories = new SelectList(await genreQuery.Distinct().ToListAsync()),
				Projects = await projects.OrderBy(p => p.CreatedDate).ToListAsync()
			};
			return View(ProjectCategorie);
		}

		// GET: Projects/Details/5
		// using comments model instead of project
		[AllowAnonymous]
		public async Task<IActionResult> Details(int? id)
		{
			{
				if (id == null)
				{
					return NotFound();
				}

				var projects = _context.Projects
					.Where(m => m.ProjectId == id)
					.Include(p => p.Category)
					.Include(p => p.ParentProject)
					.Include(p => p.Status);
				//THANG GOES HERE
				//if (User.IsInRole("Admin"))
				//{
				//	projects = _context.Projects
				//	.Where(m => m.ProjectId == id)
				//	.Include(p => p.Category)
				//	.Include(p => p.ParentProject)
				//	.Include(p => p.Status);
				//}

				foreach (var p in projects)
				{
					if (p.StatusId == 1 && !User.IsInRole("Admin"))
					{
						return RedirectToAction(nameof(Index));
					}
				}

					//var projects = _context.Projects
					//.Where(m => m.ProjectId == id && m.StatusId != 1)
					//.Include(p => p.Category)
					//.Include(p => p.ParentProject)
					//.Include(p => p.Status);
				if (projects == null)
				{
					return RedirectToAction(nameof(Index));
					return NotFound();
				}
				var children = _context.Projects.Where(p => p.ParentProjectId == id).Where(p => p.StatusId!= 1).OrderByDescending(p => p.CreatedDate).ToList();
				if (children.Count() == 0) children = null;
				var savedProjects = _context.SavedProjects.SingleOrDefault(s => s.UserName == User.Identity.Name && s.ProjectId == id);
				if (savedProjects == null)
				{
					ViewBag.isLike = false;
				}
				else
				{
					ViewBag.isLike = true;
				}
				//Update view count
				var prj = await _context.Projects.FindAsync(id);
				if (prj != null)
				{
					prj.ViewCounts += 1;
					_context.SaveChanges();
				}

				// find all comments with the project ID
				var comments = _context.Comments.Where(p => p.ProjectId == id);
				ViewData["Children"] = children;
				ViewData["Projects"] = projects;
				ViewBag.id = id;
				return View(comments);
			}
		}


		// GET: Projects/Create
		public IActionResult Create(int? ParentProjectId)
		//passing ParentProjectId when create child project
		{
			ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoriesId", "CategoriesName");
			ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "StatusName");
			ViewBag.ParentProjectId = ParentProjectId;
			return View(new ProjectUpload());
		}

		// POST: Projects/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(ProjectUpload projectUpload)
		{
			//Validate according to the upload model
			if (ModelState.IsValid)
			{
				//Create a project model and bind everything from upload to the new model
				var project = new Projects();
				project.ProjectName = projectUpload.ProjectName;
				project.UserName = User.Identity.Name;
				project.CreatedDate = DateTime.Now;
				project.BodyContent = projectUpload.BodyContent;
				project.Files = projectUpload.Files;
				project.Images = projectUpload.Images;
				project.ViewCounts = 0;
				project.LikeCounts = 0;
				project.StatusId = 1;
				project.ParentProjectId = projectUpload.ParentProjectId;
				project.Tags = projectUpload.Tags;
				project.CategoryId = projectUpload.CategoryId;

				_context.Add(project);
				await _context.SaveChangesAsync();
				//return View("index");

				//return RedirectToAction("Details", new { id = projectUpload.ProjectId });

				return RedirectToAction(nameof(Index));
			}
			ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoriesId", "CategoriesName", projectUpload.CategoryId);
			//ViewData["ParentProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectName", projectUpload.ParentProjectId);
			ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "StatusName", projectUpload.StatusId);
			return View("index");
		}

		[HttpPost]
		public async Task<string> UploadImg(IFormFile file)
		{
			var uploads = Path.Combine(hostingEnvironment.WebRootPath, "upload/img");

			if (file.Length > 0)
			{
				var f = file.FileName;
				f = f.Replace(" ", "");
				f = f.Replace("/", "");
				f = f.Replace("\\", "");
				f = f.Replace("#", "");
				var fn = Guid.NewGuid() + "_" + Uri.EscapeUriString(f);
				using (var fileStream = new FileStream(Path.Combine(uploads, fn), FileMode.Create))
				{
					await file.CopyToAsync(fileStream);
					return fn;
				}
			}
			else
			{
				return null;
			}
		}

		[HttpPost]
		public async Task<string> UploadFile(IFormFile file)
		{
			var uploads = Path.Combine(hostingEnvironment.WebRootPath, "upload/files");

			if (file.Length > 0)
			{
				var f = file.FileName;
				f = f.Replace(" ", "");
				f = f.Replace("/", "");
				f = f.Replace("\\", "");
				f = f.Replace("#", "");
				var fn = Guid.NewGuid() + "_" + Uri.EscapeUriString(f);
				using (var fileStream = new FileStream(Path.Combine(uploads, fn), FileMode.Create))
				{
					await file.CopyToAsync(fileStream);
					return fn;
				}
			}
			else
			{
				return null;
			}
		}

		[HttpPost]
		public async Task<string> DeleteFile(string id)
		{
			var uploads = Path.Combine(hostingEnvironment.WebRootPath, "upload/files");
			var fn = id;

			var filepath = Path.Combine(uploads, fn);
			if (System.IO.File.Exists(filepath))
			{
				// If file found, delete it    
				System.IO.File.Delete(filepath);
				Console.WriteLine("File deleted.");
				return "";
			}
			else
			{
				return "File does not exist";
			}
		}

		[HttpPost]
		public async Task<string> DeleteImg(string id)
		{
			var uploads = Path.Combine(hostingEnvironment.WebRootPath, "upload/img");
			var fn = id;

			var filepath = Path.Combine(uploads, fn);
			if (System.IO.File.Exists(filepath))
			{
				// If file found, delete it    
				System.IO.File.Delete(filepath);
				Console.WriteLine("File deleted.");
				return "";
			}
			else
			{
				return "File does not exist";
			}
		}

		[HttpGet()]
		public IActionResult DownloadFile(string id)
		{
			var fileFolder = Path.Combine(hostingEnvironment.WebRootPath, "upload/files/");
			string path = fileFolder;
			byte[] fileBytes = System.IO.File.ReadAllBytes(path + id);
			string fileName = id.Substring(id.IndexOf("_") + 1);
			return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
		}

		//// GET: Projects/Edit/5
		//public async Task<IActionResult> Edit(int? id)
		//{
		//	if (id == null)
		//	{
		//		return NotFound();
		//	}

		//	var projects = await _context.Projects.FindAsync(id);
		//	if (projects == null)
		//	{
		//		return NotFound();
		//	}
		//	ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoriesId", "CategoriesName", projects.CategoryId);
		//	ViewData["ParentProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectName", projects.ParentProjectId);
		//	ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "StatusName", projects.StatusId);
		//	return View(projects);
		//}

		//// POST: Projects/Edit/5
		//// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		//// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public async Task<IActionResult> Edit(int id, [Bind("ProjectId,ProjectName,UserName,CreatedDate,BodyContent,Files,Images,ViewCounts,LikeCounts,StatusId,ParentProjectId,Tags,CategoryId")] Projects projects)
		//{
		//	if (id != projects.ProjectId)
		//	{
		//		return NotFound();
		//	}

		//	if (ModelState.IsValid)
		//	{
		//		try
		//		{
		//			_context.Update(projects);
		//			_context.SaveChanges();
		//			//await _context.SaveChangesAsync();
		//		}
		//		catch (DbUpdateConcurrencyException)
		//		{
		//			if (!ProjectsExists(projects.ProjectId))
		//			{

Controllers/SavedProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using onni.Models;

namespace onni.Controllers
{
    [Authorize]
    public class SavedProjectsController : Controller
    {
        private readonly ChangeMakingContext _context;

        public SavedProjectsController(ChangeMakingContext context)
        {
            _context = context;
        }

        // GET: SavedProjects
        public async Task<IActionResult> Index()
        {
            var changeMakingContext = _context.SavedProjects.Include(s => s.Project);
            return View(await changeMakingContext.ToListAsync());
        }

        // GET: SavedProjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var savedProjects = await _context.SavedProjects
                .Include(s => s.Project)
                .FirstOrDefaultAsync(m => m.SavedId == id);
            if (savedProjects == null)
            {
                return NotFound();
            }

            return View(savedProjects);
        }

        // GET: SavedProjects/Create
        public IActionResult Create()
        {
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectName");
            return View();
        }

        // POST: Like Button
        // Like
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Like( string UserName, int ProjectId)
        {
            var savedProject = new SavedProjects
            {
                UserName = UserName,
                ProjectId = ProjectId,
                SavedDate = DateTime.Now
            };
                _context.SavedProjects.Add(savedProject);
                _context.SaveChanges();
            var project = _context.Projects.SingleOrDefault(p => p.ProjectId == ProjectId);
            var savedCount = _context.SavedProjects.Where(p=>p.ProjectId == ProjectId).Count();
            project.LikeCounts = savedCount;
            _context.SaveChanges();



            return RedirectToAction("Details", "Projects", new { id = ProjectId });
        }
        // Unlike 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Unlike(string UserName, int ProjectId)
        {
            var savedProjects = _context.SavedProjects.SingleOrDefault(s => s.UserName == UserName && s.ProjectId == ProjectId);
            _context.SavedProjects.Remove(savedProjects);
            _context.SaveChanges();
            var project = _context.Projects.SingleOrDefault(p => p.ProjectId == ProjectId);
            var savedCount = _context.SavedProjects.Where(p => p.ProjectId == ProjectId).Count();
            project.LikeCounts = savedCount;
            _context.SaveChanges();
            return RedirectToAction("Details", "Projects", new { id = ProjectId });
        }





        // POST: SavedProjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SavedId,UserName,ProjectId,SavedDate")] SavedProjects savedProjects)
        {
            if (ModelState.IsValid)
            {
                _context.Add(savedProjects);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectName", savedProjects.ProjectId);
            return View(savedProjects);
        }

        // GET: SavedProjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var savedProjects = await _context.SavedProjects.FindAsync(id);
            if (savedProjects == null)
            {
                return NotFound();
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectName", savedProjects.ProjectId);
            return View(savedProjects);
        }

        // POST: SavedProjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SavedId,UserName,ProjectId,SavedDate")] SavedProjects savedProjects)
        {
            if (id != savedProjects.SavedId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(savedProjects);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SavedProjectsExists(savedProjects.SavedId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectName", savedProjects.ProjectId);
            return View(savedProjects);
        }

        // GET: SavedProjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var savedProjects = await _context.SavedProjects
                .Include(s => s.Project)
                .FirstOrDefaultAsync(m => m.SavedId == id);
            if (savedProjects == null)
            {
                return NotFound();
            }

            return View(savedProjects);
        }

        // POST: SavedProjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var savedProjects = await _context.SavedProjects.FindAsync(id);
            _context.SavedProjects.Remove(savedProjects);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SavedProjectsExists(int id)
        {
            return _context.SavedProjects.Any(e => e.SavedId == id);
        }
    }
}

Views/Projects/Delete.cshtml
@model onni.Models.Projects

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Projects</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BodyContent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BodyContent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Files)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Files)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Images)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Images)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ViewCounts)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ViewCounts)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LikeCounts)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LikeCounts)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tags)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.CategoriesName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ParentProject)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ParentProject.BodyContent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status.StatusName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProjectId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Projects/Details.cshtml
@model IEnumerable<onni.Models.Comments>
@inject UserManager<IdentityUser> UserManager


@{
    ViewData["Title"] = "Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div data-page="project-details">
        @foreach (var item in (IEnumerable<Projects>)ViewData["Projects"])
        {
            // Display "Publish" button if login as admin and project is pending
            @if (User.IsInRole("Admin") && @item.StatusId == 1)
            {
                <div>
                    <div class="alert alert-primary">
                        <a asp-area="Admin" asp-action="Public" asp-route-id="@item.ProjectId" class="btn btn-primary mr-3">Publish</a>
                        This project has not yet been approved, and isn't publicly visible
                    </div>
                </div>
            }
            
            @if (UserManager.GetUserName(User) == item.UserName)
            {
                <div class="btn-group">
                    <a class="btn icon-btn btn-outline-secondary" asp-action="Edit" asp-route-id="@item.ProjectId">
                        <span class="icons edit mr-2"></span>
                        Edit Project
                    </a>
                    <a class="btn icon-btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.ProjectId">
                        <span class="icons delete-icon mr-2"></span>
                        Delete Project
                    </a>
                </div>
            }

    <div class="project pt-4">

        @*project title and author *@

        <div class="title-author">
            <h2 class="display-4">
                @Html.DisplayFor(modelItem => item.ProjectName)
            </h2>
            <hr />
        </div>

        @*@if (User.Identity.IsAuthenticated)
        {
            <a asp-action="Create" asp-route-ParentProjectId="@item.ProjectId">Create Child project</a>
        }*@

        <!-- Main project card -->

        <div class="card">
            <!-- Header contains categories and views and likes -->
            <div class="card-header btn-group">
                <button class="icon-btn btn btn-outline-info no-hover">
                    <span class="icons @Html.DisplayFor(modelItem => item.Category.CategoriesName)"></span>
                    @Html.DisplayFor(modelItem => item.Category.CategoriesName)
                </button>
                <div class="btn-group">
                    <button class="icon-btn btn btn-outline-secondary no-hover">
                        <span class="icons eye"></span>
                        @Html.DisplayFor(modelItem => item.ViewCounts)
                    </button>
                    <button class="icon-btn btn btn-outline-secondary no-hover">
                        <span class="icons heart"></span>
                        @Html.DisplayFor(modelItem => item.LikeCounts)
                    </button>
                </div>

                <div class="ml-auto">

                    <a href="#" class="btn text-right" id="action-user">
                        <img src="~/images/icons/user.svg" alt="profile" height="20" />
                        @Html.DisplayFor(modelItem => item.UserName)
                    </a>
                    <span class="ml-1">@Html.DisplayFor(modelItem => item.CreatedDate)</span>

                </div>

            </div>
            <!-- Body contains the various sectioned content pieces -->
            <div class="card-body">
                <!-- Background brief section -->
                <section class="project-background">
                    <h2 class="display-4">Description</h2>
                    <hr />

                    <div id="bodyContent-input" style="display:none" class="pl-3">
                        @Html.DisplayFor(modelItem => item.BodyContent)
                    </div>
                    <div class="pl-5" id="bodyContent-output">
                    </div>
                </section>

                <!-- Gallery section (may need additional classes?) -->
                @if (item.Images != null)
                {
                    <section class="project-gallery mt-4 pt-4">
                        <h2 class="display-4">Gallery</h2>
                        <hr />

                        <div class="project-gallery pl-3" id="project-images">
                            @item.Images
                        </div>
                    </section>
                }

                <!-- Downloads section -->
                @if (item.Files != null)
                {
                    <section class="project-downloads mt-4 pt-4">
                        <h2 class="display-4">Downloads</h2>
                        <hr />

                        <div class="file-uploads m-3" id="project-files">
                            @Html.DisplayFor(modelItem => item.Files)
                        </div>
                    </section>
                }

                @*ParentProject*@
                @if (item.ParentProject != null)
                {
                    <hr />
                    <p class="text-muted">
                        Child project of <a asp-action="Details" asp-route-id="@item.ParentProject.ProjectId">@item.ParentProject.ProjectName</a>
                    </p>
                }
                @if ((IEnumerable<Projects>)ViewData["Children"] != null)
                {
                    <h2 class="display-4 mt-4 pt-4">Child Projects</h2>

                    <div class="horizontal-scroll-container mt-4">
                        @foreach (var child in (IEnumerable<Projects>)ViewData["Children"])
                        {
                            <div class="horizontal-scroll-item col-sm-3">
                                <div class="card mb-3 p-0 ">
                                    <!-- Thumbnail at the top of the card -->
                                    <div class="project-thumbnail" style="height: 130px;">
                                        @if (child.Images != null)
                                        {
                                            string pic = child.Images.Trim().Split(" ")[0];
                                            @if (pic != null && pic != "" && pic != " ")
                                            {
                                                <img class="img-fluid" src="/upload/img/@pic" alt="" />
                                            }
                                        }
                                        else
                                        {
                                            <img class="img-fluid" src="https://via.placeholder.com/640x400.png?text=No+Image" alt="" />
                                        }
                                    </div>
                                    <!-- Project title -->
                                    <h3 class="card-header">
                                        <a class="text-dark" style="font-size: 0.7em;" asp-controller="Projects" asp-action="Details" asp-route-id="@child.ProjectId">@child.ProjectName</a>
                                    </h3>
                                </div>
                            </div>
                        }
                    </div>
                }
            </div>@*end card-body*@
        </div>



        <!-- Bar containing user, comments, likes, etc links, rendered as a large pill-styled bar in the mockup -->
        <div class="action-bar btn-group mt-4" role="group">
            @if (User.Identity.IsAuthenticated)
            {
                <a asp-action="Create" asp-route-ParentProjectId="@item.ProjectId" class="btn icon-btn btn-outline-primary">
                    <span class="icons plus"></span>
                    Child project
                </a>
            }
            <!-- User link, should take up twice the space of other items in the bar -->
            <!-- Comments link -->
            <a href="#creat-comment" class="btn icon-btn btn-outline-secondary text-dark" id="action-comment">
                <span class="icons reply"></span>
                Comment
            </a>
            <!-- Like button -->
            @if (ViewBag.isLike == true)
            {
                <form class="btn btn-outline-secondary" asp-controller="SavedProjects" asp-action="Unlike" asp-route-ProjectId="@item.ProjectId" asp-route-UserName="@User.Identity.Name" method="post">
                    <button type="submit" class="icon-btn text-dark btn-outline-secondary" style="background-color: transparent; border: none;">
                        <span class="icons unlike"></span>
                        Unlike
                    </button>
                </form>
            }
            else
            {
                <form class="btn btn-outline-secondary" asp-controller="SavedProjects" asp-action="Like" asp-route-ProjectId="@item.ProjectId" asp-route-UserName="@User.Identity.Name" method="post">
                    <button type="submit" class="icon-btn btn-outline-secondary text-dark"  style="background-color: transparent; border: none;">
                        <span class="icons like"></span>
                        Like
                    </button>
                </form>

            }
            @if (User.Identity.Name == item.UserName)
            {
                <a class="btn icon-btn btn-outline-secondary text-dark" asp-action="Edit" asp-route-id="@item.ProjectId">
                    <span class="icons edit"></span>

                    Edit
                </a>

            }
        </div>

    </div> <!-- End of project -->
        }
        <div class="comments mt-5 pb-3">
            <h2 >Project Discussion</h2>
            <partial name="_DisplayComments" />
            <partial name="_CreateComment" />
        </div>

    </div>


<script src="/lib/jquery/dist/jquery.js"></script>
<script>
    var imgSection = $("#project-images")
    var fileSection = $("#project-files")
    var images = imgSection.text().trim().split(" ")
    var files = fileSection.text().trim().split(" ")
    var imgContent = ""
    var fileContent = ""

    if (images != "") {
        $.each(images, function (index, img) {
            //Image HTML goes here!
            imgContent += "<div class='img-container'><a href='../../upload/img/" + img + "' target='_blank'><img src = '/upload/img/" + img + "' alt = '' /></a></div>"
        })
    }
    else {
        imgContent = "<p>No Images</p>"
    }
    imgSection.html(imgContent)

    if (files != "") {
        $.each(files, function (index, file) {
            var plainName = file.substring(file.indexOf("_") + 1);
            //File display HTML goes here!
            fileContent += "<p class=''><a target='_blank' href='../DownloadFile/" + file + "'>" + plainName + "</a></p>"
        })
    }
    fileSection.html(fileContent);
</script>